import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createPublicClient,createWalletClient,custom,http,parseEventLogs} from 'viem';
import {bscTestnet} from 'viem/chains';
import './styles.css';
type Agent={key:string;agentId:string;agentRegistry:string;name:string;description:string;owner?:string;categories:string[];skills:any[];endpoints:{type:string;url:string}[];reputation:any};
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
const commerce='0xa206c0517b6371c6638cd9e4a42cc9f02a33b0de' as `0x${string}`; const router='0xd7d36d66d2f1b608a0f943f722d27e3744f66f25' as `0x${string}`; const zero='0x0000000000000000000000000000000000000000' as `0x${string}`;
const commerceAbi=[{type:'function',name:'createJob',stateMutability:'nonpayable',inputs:[{name:'provider',type:'address'},{name:'evaluator',type:'address'},{name:'expiredAt',type:'uint256'},{name:'description',type:'string'},{name:'hook',type:'address'}],outputs:[{type:'uint256'}]},{type:'function',name:'fund',stateMutability:'nonpayable',inputs:[{name:'jobId',type:'uint256'},{name:'expectedBudget',type:'uint256'},{name:'optParams',type:'bytes'}],outputs:[]},{type:'function',name:'paymentToken',stateMutability:'view',inputs:[],outputs:[{type:'address'}]},{type:'event',name:'JobCreated',inputs:[{indexed:true,name:'jobId',type:'uint256'},{indexed:true,name:'client',type:'address'},{indexed:true,name:'provider',type:'address'},{indexed:false,name:'evaluator',type:'address'},{indexed:false,name:'expiredAt',type:'uint256'},{indexed:false,name:'hook',type:'address'}]}] as const;
const routerAbi=[{type:'function',name:'registerJob',stateMutability:'nonpayable',inputs:[{name:'jobId',type:'uint256'},{name:'policy',type:'address'}],outputs:[]}] as const;
const erc20Abi=[{type:'function',name:'approve',stateMutability:'nonpayable',inputs:[{name:'spender',type:'address'},{name:'amount',type:'uint256'}],outputs:[{type:'bool'}]},{type:'function',name:'decimals',stateMutability:'view',inputs:[],outputs:[{type:'uint8'}]}] as const;
function App(){
 const [agents,setAgents]=useState<Agent[]>([]),[cat,setCat]=useState('all'),[account,setAccount]=useState<`0x${string}`>(),[selected,setSelected]=useState<Agent>(),[busy,setBusy]=useState(''),[jobId,setJobId]=useState(''),[record,setRecord]=useState<any>(),[error,setError]=useState('');
 const pub=useMemo(()=>createPublicClient({chain:bscTestnet,transport:http()}),[]);
 useEffect(()=>{fetch(`${API}/api/agents?limit=100`).then(r=>r.json()).then(x=>setAgents(x.agents||[])).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!jobId)return;const t=setInterval(()=>fetch(`${API}/api/jobs/${jobId}`).then(r=>r.ok?r.json():null).then(setRecord).catch(()=>{}),5000);return()=>clearInterval(t)},[jobId]);
 const shown=cat==='all'?agents:agents.filter(a=>a.categories.includes(cat));
 async function connect(){try{const eth=(window as any).ethereum;if(!eth)throw Error('Install a browser wallet such as MetaMask.');const w=createWalletClient({chain:bscTestnet,transport:custom(eth)});const [a]=await w.requestAddresses();const chain=await w.getChainId();if(chain!==97)throw Error('Switch your wallet to BNB Smart Chain Testnet (chain 97).');setAccount(a)}catch(e:any){setError(e.shortMessage||e.message)}}
 async function hire(){if(!selected||!account)return;setError('');setBusy('Validating agent…');try{const prepRes=await fetch(`${API}/api/hire/prepare`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agent_id:selected.agentId,agent_registry:selected.agentRegistry,client:account,description:`AgentForge task for ${selected.name}: execute the selected agent capability and return a structured result.`})});const prep=await prepRes.json();if(!prepRes.ok)throw Error(prep.detail||'Agent validation failed');if(!prep.provider||prep.provider===zero)throw Error('This registration does not expose a provider wallet and cannot be hired through ERC-8183.');const eth=(window as any).ethereum;const w=createWalletClient({account,chain:bscTestnet,transport:custom(eth)});const expiry=BigInt(Math.floor(Date.now()/1000)+1800);setBusy('Creating ERC-8183 job…');const tx=await w.writeContract({address:commerce,abi:commerceAbi,functionName:'createJob',args:[prep.provider as `0x${string}`,router,expiry,`AgentForge:${selected.agentRegistry}:${selected.agentId}`,router]});const rc=await pub.waitForTransactionReceipt({hash:tx});const logs=parseEventLogs({abi:commerceAbi,eventName:'JobCreated',logs:rc.logs});const id=logs[0]?.args.jobId;if(id===undefined)throw Error('JobCreated event was not found.');setJobId(id.toString());await fetch(`${API}/api/jobs/${id}/record`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({agent_id:selected.agentId,agent_registry:selected.agentRegistry,client:account,description:selected.description})});setBusy('Registering job with ERC-8183 Router…');const rtx=await w.writeContract({address:router,abi:routerAbi,functionName:'registerJob',args:[id,'0x4f4678d4439fec812ac7674bb3efb4c8f5fb78a6']});await pub.waitForTransactionReceipt({hash:rtx});setBusy('Provider is pricing the job…');const br=await fetch(`${API}/api/jobs/${id}/budget`,{method:'POST'});if(!br.ok)throw Error((await br.json()).detail||'Provider could not budget the job.');const token=await pub.readContract({address:commerce,abi:commerceAbi,functionName:'paymentToken'});const decimals=await pub.readContract({address:token as `0x${string}`,abi:erc20Abi,functionName:'decimals'});const amount=10n**BigInt(decimals);setBusy('Approving payment token…');const atx=await w.writeContract({address:token as `0x${string}`,abi:erc20Abi,functionName:'approve',args:[commerce,amount]});await pub.waitForTransactionReceipt({hash:atx});setBusy('Funding escrow…');const ftx=await w.writeContract({address:commerce,abi:commerceAbi,functionName:'fund',args:[id,amount,'0x']});await pub.waitForTransactionReceipt({hash:ftx});setBusy('Funded — waiting for provider execution…')}catch(e:any){setError(e.shortMessage||e.message||String(e))}finally{setBusy('')}}
 return <div className="shell"><header><div className="brand"><span>AGENT</span>FORGE</div><div className="network">BSC TESTNET <i/></div><button onClick={connect} className="wallet">{account?account.slice(0,6)+'…'+account.slice(-4):'Connect wallet'}</button></header><main><section className="hero"><div><p className="eyebrow">THE BNB AGENT MARKETPLACE</p><h1>Hire intelligence.<br/><em>On-chain.</em></h1><p className="sub">Discover live ERC-8004 agents on BNB Chain, compare capabilities, and activate them through trustless ERC-8183 commerce.</p></div><div className="orb"><div className="ring r1"/><div className="ring r2"/><div className="core">AF</div></div></section><nav className="cats">{[['all','All agents'],['rebalancing','Rebalancing'],['grid-trading','Grid trading'],['yield-optimization','Yield optimisation'],['health-factor','Health factor']].map(([k,v])=><button className={cat===k?'active':''} onClick={()=>setCat(k)} key={k}>{v}</button>)}</nav><div className="bar"><span>{shown.length} discovered</span><span>LIVE ERC-8004 REGISTRY · CHAIN 97</span></div>{error&&<div className="error">{error}</div>}<section className="grid">{shown.map(a=><article className="card" key={a.key} onClick={()=>setSelected(a)}><div className="cardtop"><span>#{a.agentId}</span><span className="live">● LIVE</span></div><h2>{a.name}</h2><p>{a.description}</p><div className="chips">{a.categories.slice(0,3).map(c=><span key={c}>{c.replaceAll('-',' ')}</span>)}</div><footer><span>{a.endpoints.length} endpoint{a.endpoints.length!==1?'s':''}</span><button>View agent ↗</button></footer></article>)}</section></main>{selected&&<div className="backdrop" onClick={()=>!busy&&setSelected(undefined)}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(undefined)}>×</button><p className="eyebrow">ERC-8004 AGENT</p><h2>{selected.name}</h2><p className="desc">{selected.description}</p><div className="facts"><div><small>IDENTITY</small><b>{selected.agentRegistry}:{selected.agentId}</b></div><div><small>CAPABILITIES</small><b>{selected.skills.length?selected.skills.join(', '):selected.categories.join(', ')||'Declared in registration'}</b></div><div><small>ENDPOINTS</small><b>{selected.endpoints.map(e=>e.type).join(' · ')||'None'}</b></div></div><div className="hirebox"><div><span>Service budget</span><strong>1 U</strong></div><p>ERC-8183 escrow · BSC testnet</p><button disabled={!account||!!busy} onClick={hire}>{busy||(!account?'Connect wallet to hire':'Hire agent')}</button></div>{jobId&&<div className="timeline"><b>JOB #{jobId}</b><span>{record?.status||'created'}</span>{record?.result&&<pre>{JSON.stringify(record.result,null,2)}</pre>}</div>}</aside></div>}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
